sudo: false

language: java

script:
  - mvn clean package

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && mvn package -DskipTests && mvn docker:build && mvn docker:push
  on:
    branch: master
